# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 5m
  modules-download-mode: readonly
  skip-files:
    - ".*\\.gen\\.go$"
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - ineffassign
    - gosimple
    - gofmt
    - revive

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true
    exclude: errcheck_excludes.txt
